inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'fits-*/**/**'
    - 'db/**/*.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'app/importers/californica_csv_cleaner.rb'
    - app/jobs/hyrax/characterize_job.rb
    - app/importers/actor_record_importer.rb
    - app/uploaders/csv_manifest_validator.rb
    - app/importers/collection_record_importer.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/importers/californica_mapper.rb'
    - 'app/jobs/hyrax/characterize_job.rb'
    - 'app/uploaders/csv_manifest_validator.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/ingest.rake'
    - 'lib/tasks/derivatives.rake'
    - app/models/ucla_metadata.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/importers/californica_mapper.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - app/uploaders/csv_manifest_validator.rb
    - app/importers/actor_record_importer.rb
    - app/importers/californica_csv_parser.rb

Metrics/LineLength:
  Exclude:
    - 'app/importers/collection_record_importer.rb'
    - 'spec/tasks/ingest_spec.rb'
    - 'app/importers/rights_statement_validator.rb'
    - 'spec/system/import_and_show_work_spec.rb'
    - app/importers/actor_record_importer.rb
    - app/controllers/catalog_controller.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/importers/californica_csv_parser.rb'
    - app/importers/actor_record_importer.rb
    - app/forms/hyrax/californica_collections_form.rb
    - 'app/importers/csv_validator.rb'
    - app/uploaders/csv_manifest_validator.rb

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - app/importers/actor_record_importer.rb
    - 'app/uploaders/csv_manifest_validator.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/system**/*'
    - 'spec/tasks/ingest_spec.rb'
    - 'spec/importers/californica_mapper_spec.rb'
    - 'spec/importers/californica_importer_spec.rb'
    - 'spec/importers/collection_record_importer_spec.rb'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'
    - spec/jobs/start_csv_import_job_spec.rb

RSpec/LetSetup:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/importers/csv_validator.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/importers/californica_importer_spec.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'
    - 'spec/system/search_crawler_spec.rb'
    - 'spec/tasks/**/*'
