inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - app/forms/hyrax/californica_collections_form.rb

Metrics/AbcSize:
  Enabled: true
  Max: 30
  Exclude:
    - app/importers/californica_csv_cleaner.rb
    - app/jobs/hyrax/characterize_job.rb
    - app/importers/actor_record_importer.rb
    - app/uploaders/csv_manifest_validator.rb
    - app/importers/collection_record_importer.rb
    - spec/jobs/mss_csv_import_job_spec.rb
    - app/jobs/csv_row_import_job.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/models/solr_document.rb
    - app/controllers/catalog_controller.rb
    - app/controllers/catalog_controller.rb
    - app/importers/californica_mapper.rb
    - app/importers/californica_mapper.rb
    - app/jobs/hyrax/characterize_job.rb
    - app/uploaders/csv_manifest_validator.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'app/uploaders/csv_manifest_validator.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/ingest.rake'
    - 'lib/tasks/derivatives.rake'
    - 'lib/tasks/purge.rake'
    - app/models/ucla_metadata.rb
    - app/views/manifest.json.jbuilder

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - app/models/ucla_metadata.rb

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - app/uploaders/csv_manifest_validator.rb
    - app/importers/actor_record_importer.rb
    - app/importers/californica_csv_parser.rb
    - app/models/concerns/discoverable.rb
    - app/indexers/collection_indexer.rb

Metrics/LineLength:
  Exclude:
    - 'app/importers/collection_record_importer.rb'
    - 'spec/tasks/ingest_spec.rb'
    - 'app/importers/rights_statement_validator.rb'
    - 'spec/system/import_and_show_work_spec.rb'
    - app/importers/actor_record_importer.rb
    - app/controllers/catalog_controller.rb
    - spec/renderers/iiif_viewing_hint_attribute_renderer_spec.rb

Metrics/MethodLength:
  Enabled: true
  Max: 20
  Exclude:
    - app/models/solr_document.rb
    - app/importers/californica_csv_parser.rb
    - app/importers/actor_record_importer.rb
    - app/forms/hyrax/californica_collections_form.rb
    - app/importers/csv_validator.rb
    - app/uploaders/csv_manifest_validator.rb
    - app/indexers/collection_indexer.rb
    - app/models/concerns/discoverable.rb
    - app/presenters/hyrax/californica_collection_presenter.rb
    - app/importers/californica_importer.rb
    - app/jobs/csv_row_import_job.rb

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - app/models/ucla_metadata.rb

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - app/importers/actor_record_importer.rb
    - app/uploaders/csv_manifest_validator.rb
    - app/importers/californica_csv_parser.rb
    - app/models/concerns/discoverable.rb
    - app/indexers/collection_indexer.rb

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/forms/hyrax/child_work_form_spec.rb'
    - 'spec/forms/hyrax/work_form_spec.rb'
    - 'spec/importers/californica_importer_spec.rb'
    - 'spec/importers/californica_mapper_spec.rb'
    - 'spec/importers/collection_record_importer_spec.rb'
    - 'spec/jobs/inherit_permissions_job_spec.rb'
    - 'spec/jobs/mss_csv_import_job_spec.rb'
    - 'spec/jobs/mss_csv_import_job_spec.rb'
    - 'spec/jobs/start_csv_import_job_spec.rb'
    - 'spec/jobs/start_csv_import_job_spec.rb'
    - 'spec/models/concerns/discoverable_spec.rb'
    - 'spec/system**/*'
    - 'spec/tasks/ingest_spec.rb'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'
    - 'spec/views**/*'
    - 'spec/views/manifest.json.jbuilder_spec.rb'

RSpec/LetSetup:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/importers/csv_validator.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/importers/californica_importer_spec.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/system/search_catalog_spec.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/importers/californica_importer.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'
    - 'spec/system/search_crawler_spec.rb'
    - 'spec/tasks/**/*'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/importers/californica_mapper_spec.rb'

# Controlling flow w/ guard clauses can be overly clever and makes code harder to read - ABW
Style/GuardClause:
  Enabled: false

Style/Next:
  Exclude:
    - 'app/uploaders/csv_manifest_validator.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/hyrax/works_controller.rb'
