inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features**/*'
