inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/ingest.rake'

Metrics/LineLength:
  Exclude:
    - 'spec/tasks/ingest_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features**/*'
    - 'spec/tasks/ingest_spec.rb'
    - 'spec/importers/californica_mapper_spec.rb'
