inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/importers/californica_mapper.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/ingest.rake'
    - 'lib/tasks/derivatives.rake'

Metrics/LineLength:
  Exclude:
    - 'spec/tasks/ingest_spec.rb'
    - 'app/importers/rights_statement_validator.rb'
    - 'spec/features/import_and_show_work_spec.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/importers/californica_csv_parser.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features**/*'
    - 'spec/tasks/ingest_spec.rb'
    - 'spec/importers/californica_mapper_spec.rb'

RSpec/NotToNot:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - 'spec/features/search_catalog_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/features/search_catalog_spec.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/features/search_catalog_spec.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/features/search_catalog_spec.rb'

Naming/PredicateName:
  Exclude:
    - 'app/indexers/year_parser.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/indexers/year_parser.rb'
