language: ruby
sudo: false
cache: bundler
dist: trusty
jdk:
- oraclejdk8
rvm:
- 2.5
env:
- DATABASE_USERNAME=travis
- secure: pdi/VpMnW1WtSqnz6SsPTUnhzC2uYrNDHeqSW6DmHyDr83Dn4t6njbPiUgnVTVBSO3hILI9z9ppeKMygtZ9SARUrj5DpGMs+Khk1LlT+Qai5kCaCNYGRQiRmR8rVqdkUpvOplia7kGDhpaoCpw6lnlr8mdwPVuERYaE4gjFsmTfB63WzWbO3g98zEfG9qH7rGgXAn5fbgxGP0lued88fdyLnGcgmiYq38b2UHslg5iydTuJChNWIH669rJGkz/tyN3EUTi7VtHxkB44bAbMRhZVITmf6YF6Y8tgZOYaTYWQWEHP/UjryA0iCd0DJDG36Pt5nuy67jWpOhvOKtZAeYFFrC38ni/owRQ8LkD18hqfqgIqyzcKKxJKqY77axH9mqjfS0I/UBi6cuiDi5cQzLPPbxeg6NhvZuQ3WfgJEUQmaXTYeK3kFC9hO1SLnmPn+B0NC387RmegQq0LwKqDWYN90cJK/GmjTNodKvYU4bqJcVc2JNuMg9HpK7Dfb4lezFmtpTUccOgDEVqe5B8yqIh/dcRCWZ63Eoj/8Evz4vPXKJhF50QY7QQZVNColttXzW+rCUTUygMjugOnSSd18V4bgs04V0FDjf/Bi8yxJ2H6wL7UD46YEV1gaEslTC+qkfbUqmAU71Mc2qkoB4h22GTtmzrUFYFzcnl4jZN05mbc=
- secure: WGPE7kv00BUJZOP+4oL6AOpaZgtdVllJCTyd8Nb31UFqM5R+Z2YoeqUffpBIrlqrZJQB1ENZp92oY6WH8ybk4zhkAdQbcHhyxWqwunTdKWwTdGjBBVzxK5u7XMRKLGVpjeIq3qc8xGIvEjSaIsJJQE5cCvkgj3Jga88bBRKTwTv/LRp87Dms0Q3HofMU1cHR01nD5bWI4sU9REyUhHQ3mI5dXxBiHGPLcE+kNTgLyF4dOH+dMHONlqK6UlP5/engxQ6FTF4z4JF/1g2IL1vy3WeamTjy8vFYxSFeYodcts0ZyyqGg2ltBhfjgWvEB3Z8A8Y3j+zj1DHus34zEiKZbwfcr2KYx5nYFGuJbm1uhg1fBqIC1wLOd0QrDu5Q6KS7iffBcAkklRVlTgSs5ceZWSbpu+BmAxnCT/w+ymiO8eHFMh2Y/H6VfsXTtHVcJqoncUjIYmtZBDIM020IRa84ZJsZw/RKLmvs2blza3jWOvsKopQaTjacxIFbcTYlC56oNw0hbRqFQXEhQgxH5HtYXWQOT6adVlM2luOX4/7kPyVqSVMrjiy/ba2lOoiR+tV6eG7STqN6ZR9ztIfGMzu1lWftspvjsZ9kih6TCqfBwd0ZJL9e/22gNna9CPfCtDpl2x5jxsGQ2F926NCMm7YFQPEDJndGD2DXj23fZVhY61w=
- secure: Ie1OPm8i75BBO4TNSRU4ADnkJanNCbomVhPJ10VS9heXqwzR+/YmJ+ynq/yt+sRMMuYifewZ/Hfda+y0o5O27LDh9vteSf2ZIKwMx4Nb5UwQ/mstp44SrmzWx0rnsI10uNTlsnrliD1ZAi187RIEgAQamXN06VD/aLWcapc4AU0qPlBHx+B7OfDT3lbfyiHKZNSpx2z5cZH+jucYiIYuTkj5UtuCvjfS166/zi2Tme8cxSkrTYDjun4JTiRCgJ13idubpe1LPmwdBtP12XEtb/3sc7z0X7Y+vBsggD346O4JrVRSQao+Hu6Up+C+7nafEkdp9hqY7uklSj74Vyx+9RP/7djOTABzxr2+nK2R40a4HM56TU+pLGdHpBUkkKuhF/i8yWwXK92OgElIRi3E86aw9oRropq7JjufB7dHASJUXUVijLdNXPeVIC8dj+e69QDi9aZGw9SlQyCTcrq9aIIDa06fGADrZ67Uwy/2DOkN0htZUsqDTE/LVhXmdHWvb6ci4XhPrgJielL3Y7dN2VrfSGznm4Zd91ei2+hh6rdrav2fvbRR64cHbAOA1xTFYLcAyA0yIIyS5kZs+3/B70E9lJzakaMiNDWU/u+wf3prYbY1VINUGeb6c61/eGCWyy0SdOR1Lq50TVHAsGm0xFNrJ5BFlnp0gIEXbuxRyzo=
- secure: QDW8zO+kQmOd87oE7FXpDTPJ3Pur249iIT47l7arnQvara+u01G7k/spEUez0EufAYc0lZZZClpZQ4UM9xgCHebsSeoocI08c6SL44fLvaK3T4da29SVM9kj7ubXC7st+zAUFRjO+lQh8suwJXd3AoMSqzsbJTd46HxQ5nTWu1bp+4kagLL6LW5NZaMmbQTEF1HajHRZu0jHGXcLxMtEo+rsHK5Evfp3HxlrdTmfypaDSdKxq8DAMHirvkXOHpv51Uk/YOgxm6mHKjR6vYRheslLFzd7r4Cxj2T9zThz/8ucVGP/iiQzz7H7U69CNLZC8SlQ8ob5sBdTfYbjH+BX4JyXyts7xKf+plykTyEH7TKLRTAQaA4i6K9D5ofO4m78yIhKej72ti3qRwJgiuT9adWj/JAHz1B+eXh5r+h3E2U4HtP9DF52vcApOIYJMAhKANXKbDac4o/WgHFzrIt63Z/l5x5Z1sJLrDJxGBhKcXh+B3VWm6HeflsAfbIy6mYj6ZL/1YfMWoCtF2sgbrLVJ1+TF1/XvAJ8IiUtbykby7qMPOFfoCTwwgNZUo1iyChUKqWTXHBdYUIQGe0MmY49WXoHKxzD/XUXsqx0n05H6pYYQpPlsfiXWFUwFw6trwAIhL2CWGhVy98dJ/nyynoCQGiQ62ryBElDKAtQ9kAFeHI=
before_script:
- bundle exec rake db:create
script:
- bundle exec rake
services:
- redis-server
- mysql
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    openssl aes-256-cbc -K $encrypted_b2e2a85c6b8e_key -iv $encrypted_b2e2a85c6b8e_iv -in ucla_deploy_rsa.enc -out ucla_deploy_rsa -d
    bundle exec cap cd deploy
  fi
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    JENKINS_CRUMB=$(wget -q --auth-no-challenge --user $JENKINS_USERNAME --password $JENKINS_PASSWORD --output-document - \
    'https://$JENKINS_HOST/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
    curl -X POST -H "$JENKINS_CRUMB" --user $JENKINS_USERNAME:$JENKINS_PASSWORD \
    'https://$JENKINS_HOST/job/DeployCalifornica/buildWithParameters?DEPLOY_HOST=$DEPLOY_HOSTNAME&GIT_BRANCH=master'
  fi
