language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - tmp/solr_downloads
    - tmp/fedora_downloads
dist: trusty
addons:
  apt:
    packages:
    - libclamav-dev
    - clamav
    - chromium-browser
    - chromium-chromedriver
jdk:
- oraclejdk8
rvm:
- 2.5
env:
  global:
    - DATABASE_USERNAME=travis
    - IIIF_SERVER_URL='http://test.url/'
before_install:
  - gem update --system
  - gem install bundler:1.17.3
before_script:
  - bundle exec rake db:create
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - bundle exec rake
services:
  - redis-server
  - mysql
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl "$JENKINS_DEPLOY_URL"
  fi
  if [[ $TRAVIS_TAG != "" ]]; then
    curl "$JENKINS_TAG_DEPLOY_URL"
  fi
