version: '2'

services:
  web:
    image: uclalibrary/californica:latest
    depends_on:
      - db
      - fedora
      - redis
      - solr
      - fedora_test
      - solr_test
    env_file:
      - ./default.env # must come first to be overloaded
      - ./docker.env # must come last to overload default
    stdin_open: true
    tty: true
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/californica
      - ./data:/opt/data
      - bundle_dir:/usr/local/bundle
      - californica_tmp:/californica/tmp
      - derivatives:/opt/derivatives
      - californica_log:/californica/log
      - tmp:/tmp
      - uploads:/opt/uploads
    working_dir: /californica

  sidekiq:
    image: uclalibrary/californica:latest
    command: ['bundle', 'exec', 'sidekiq', '-c', '2']
    depends_on:
      - db
      - fedora
      - redis
      - solr
      - fedora_test
      - solr_test
    env_file:
      - ./default.env # must come first to be overloaded
      - ./docker.env # must come last to overload default
    volumes:
      - .:/californica
      - ./data:/opt/data
      - bundle_dir:/usr/local/bundle
      - californica_log:/californica/log
      - californica_tmp:/californica/tmp
      - derivatives:/opt/derivatives
      - tmp:/tmp
      - uploads:/opt/uploads
    working_dir: /californica

  fedora:
    image: nulib/fcrepo4:4.7.5
    ports:
      - '127.0.0.1:8984:8080'
    volumes:
      - fcrepo_data:/data
    environment:
      JAVA_OPTIONS: '-Xmx512m'

  fedora_test:
    image: nulib/fcrepo4:4.7.5
    ports:
      - '127.0.0.1:8986:8080'
    environment:
      JAVA_OPTIONS: '-Xmx512m'

  db:
    image: mysql:5.6
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'

  solr:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/californica/data
    ports:
      - '127.0.0.1:8983:8983'
    environment:
      - SOLR_URSUS_URL=http://solr:8983/solr/ursus

  solr_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    ports:
      - '127.0.0.1:8985:8983'
    environment:
      - SOLR_URSUS_URL=http://solr_test:8983/solr/ursus

  # iiif:
  #   image: uclalibrary/cantaloupe
  #   environment:
  #     DELEGATE_SCRIPT.ENABLED: "true"
  #     DELEGATE_SCRIPT.PATHNAME: /docker/delegates.rb
  #     ENDPOINT.ADMIN.ENABLED: "true"
  #     ENDPOINT.ADMIN.SECRET: cobweb123
  #   ports:
  #     - 8182:8182
  #   volumes:
  #     - ./cantaloupe-delegate/lib:/delegate

volumes:
  bundle_dir:
  californica_log:
  californica_tmp:
  derivatives:
  fcrepo_data:
  mysql_data:
  redis_data:
  solr_data:
  tmp:
  uploads:
