# Note that UCLA is not authorized to use rightsstatements.org values.
# This file overrides the default URI values.
terms:
- id: http://vocabs.library.ucla.edu/rights/copyrighted
  term: "copyrighted"
  active: true
