development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/californica" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8985/solr/californica" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
