development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/<%= ENV['REDIS_CABLE_DB'] %>
  channel_prefix: <%= ENV['CABLE_CHANNEL_PREFIX'] || 'californica_production' %>
