development:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'async' %>

test:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'async' %>

production:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'redis' %>
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/<%= ENV['CABLE_REDIS_DB'] || '1' %>
  channel_prefix: <%= ENV['CABLE_CHANNEL_PREFIX'] %>
