---
  :queues:
    - [ingest, 4]
    - [batch, 2]
    - [default, 1]

  test: # n/a
    :concurrency: 2

  development:
    :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 5 %>

  production:
    :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 5 %>
