name: daily

on:
   schedule:
      - cron:  '30 14 * * *'

jobs:
    deploy:
        name: Deploy to test
        runs-on: ubuntu-latest
        steps:
        - name: Jenkins webhook
          uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
          with:
            curl: 'https://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_AUTH_TOKEN }}@${{ secrets.JENKINS_HOST }}/job/DeployCalifornica/buildWithParameters?GIT_BRANCH=main&cause=GitHub+Action+Post+Merge+Build&DEPLOY_HOST=t-w-californica01.library.ucla.edu'
