name: On merge

on:
    push:
        branches: 
            - main

jobs:
    update-pull-requests:
        name: Update pull requests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: update all prs
          uses: maxkomarychev/pr-updater-action@92cb6e15dc3c4b9b148b65eef32836bb428587b9  # v1.0.1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
    
    deploy:
        name: Deploy to test
        runs-on: ubuntu-latest
        steps:
        - name: Jenkins webhook
          uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
          with:
            curl: 'https://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_AUTH_TOKEN }}@${{ secrets.JENKINS_HOST }}/job/DeployCalifornica/buildWithParameters?GIT_BRANCH=main&cause=GitHub+Action+Post+Merge+Build&DEPLOY_HOST=t-w-californica01.library.ucla.edu'

    docker-build:
        runs-on: ubuntu-latest
        steps:
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              push: true
              tags: uclalibrary/californica:latest
              platforms: linux/amd64,linux/arm64
              build-args: FCREPO_VERSION=4.7.5
