name: On tagged release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  deploy:
    name: Deploy to stage
    runs-on: ubuntu-latest
    steps:
    - name: Branch name
      run: echo running on branch ${GITHUB_REF_NAME}
    - name: Jenkins webhook
      uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
      with:
        curl: 'https://${{ secrets.JENKINS_USER }}@${{ secrets.JENKINS_HOST }}/job/DeployCalifornica/buildWithParameters?GIT_BRANCH=${{ github.ref_name }}&cause=GitHub+Action+Build+with+tag&DEPLOY_HOST=s-w-californicaweb01.library.ucla.edu&token=${{ secrets.JENKINS_API_CALIFORNICA_TOKEN }}'